### ISSUE TITLE
sequence found inside character string

### ISSUE THREAD

**Issue by manuelcaeiro** [peberlein/WEE#5]
Hi,
Sorry to bother you again.
Since I've started learning Euphoria, +/- 2 weeks ago, the error message "sequence found inside character string" has appeared many times when I use puts or printf to output results.
As I'm new to the language I assumed I was probably making some beginner's mistake.
Then, I came across a pretty simple example that I tried both with ed (edx, to be more precise, which I've been using as a shell substitute) and I finally understood why I got so many error messages.
The script is as follows:

`sequence sent

sent = "In the sun."

printf(1, "%s\n", {sent})

--replace "I" with an "O"

sent[1] = "O"

--replace "sun." with "road."

sent = sent[1..7] & "road."

printf(1, "%s\n", {sent})`

When I ran it with with WEE I got the error message, when I ran it with ed everything worked fine.
So I comment the line "printf..." and added a line print(1, sent) on both editors.
What I get running with WEE is: {{79}, 110, 32, 116, 104, 101, 32, 114, 11, 97, 100, 46}
What I get running with ed is: {79, 110, 32, 116, 104, 101, 32, 114, 11, 97, 100, 46}
Also, if I I flatten sent on WEE script, the output is correct with no error mesages.
Shouldn't both editors output the same?
Thank you.

**Comment by peberlein** [comment]
I don't understand how this could work in edx, but the problem is here:

sent[1] = "O"

sent[1] refers to the first character in sent, but "O" is a sequence of a single character since it uses double-quote marks.  If you want a literal character use single-quote marks:

sent[1] = 'O'

Alternatively, assigning to a range of a sequence allows you to copy another sequence into that range, allowing this:

sent[1..1] = "O"

As you suspect, this is a beginner mistake, but the way strings and character literals work commonly trip up new learners.  Do not be discouraged.

**Comment by manuelcaeiro** [comment]
Thank you for your clear explanation (and your patience).
I've never been discouraged by hard learning - only by bad people sometimes.
